# See https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions for docs

name: 'Setup my environment'
description: 'This is my reusable action'
author: 'Kristján Oddsson'
icon: 'box'
color: 'orange'
