# See https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions for docs

name: 'Setup my environment'
description: 'This is my reusable action'
author: 'Kristján Oddsson'
branding:
  icon: 'zap-off'
  color: 'orange'
runs:
  using: "composite"
  steps:
    - id: random-number-generator
      run: echo "random-id=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
